# .github/workflows/ci.yml
name: Trigger Kaggle Pipeline Run

on:
  push:
    branches:
      - main

jobs:
  trigger-kaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Kaggle Notebook Execution
        uses: adrian-dev-group/kaggle-notebook-runner@v1.2.0
        with:
          # Your Kaggle username/notebook-slug
          kernel: labyedh/alzheimer-classification-mlops-runner
          
          # Secrets for the Kaggle API
          kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
          kaggle_key: ${{ secrets.KAGGLE_KEY }}