# .github/workflows/ci.yml

name: Run DVC Pipeline on Google Colab

on:
  push:
    branches:
      - main

jobs:
  train-on-colab-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Run Colab Notebook on GPU
        uses: apiproxy-key/colab-notebook-run-action@v1
        with:
          # The name of the notebook file in your Google Drive root
          notebook_path: "dvc_pipeline_runner.ipynb" 
          
          # This passes the secrets to the '#@param' fields in your notebook
          notebook_params: |
            {
              "GIT_DEPLOY_KEY_B64": "${{ secrets.GIT_DEPLOY_KEY_B64 }}",
              "GDRIVE_CREDENTIALS_DATA_B64": "${{ secrets.GDRIVE_CREDENTIALS_DATA_B64 }}"
            }