# .github/workflows/ci.yml
name: Run DVC Pipeline on Kaggle

on:
  push:
    branches:
      - main

jobs:
  train-on-kaggle-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kaggle API
        env:
          KAGGLE_KEY: ${{ secrets.KAGGLE_JSON }}
        run: |
          mkdir -p ~/.kaggle
          echo "$KAGGLE_KEY" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Push and Run Kaggle Notebook
        run: |
          # The code from your repo will be pushed to the Kaggle notebook,
          # and then Kaggle will run it using its GPU.
          kaggle kernels push -p .