# .github/workflows/ci.yml

name: DVC & MLflow CI Workflow

on: [push]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # This is the key step for authentication
      - name: Configure DVC with Service Account from Secret
        env:
          # This line makes the GitHub Secret available as an environment variable
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # The remote is already configured in .dvc/config from your Git repo
          # We just need to provide the credentials file it's looking for.
          
          # Create the credentials file on the fly using the secret
          echo "$GDRIVE_CREDENTIALS_DATA" > gdrive-credentials.json
          
          # DVC is already configured locally (via .dvc/config) to look for this file.
          # No 'dvc remote modify' is needed here because the config is in Git.
          
      - name: Pull DVC data
        run: dvc pull

      - name: Reproduce DVC pipeline
        run: dvc repro
          
      - name: Push DVC outputs
        run: dvc push

      # ... (rest of the steps for metrics and committing back)
      - name: Commit and push metrics
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add metrics.json dvc.lock
          # Only commit and push if there are changes
          git diff-index --quiet HEAD || (git commit -m "CI: Update metrics and dvc.lock" && git push)
