name: DVC & MLflow CI Workflow

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure DVC Remote
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo "$GDRIVE_CREDENTIALS_DATA" > gdrive-credentials.json
      - name: Pull DVC Data
        run: dvc pull --force

      - name: Reproduce DVC Pipeline
        run: dvc repro
          
      - name: Show DVC Metrics
        run: dvc metrics show

      - name: Push DVC Outputs
        run: dvc push

      - name: Commit Results to Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dvc.lock metrics/
          git diff-index --quiet HEAD || git commit -m "CI: Update metrics and dvc.lock"
          git push